version: '3'

services:
  web:
    depends_on:
      - redis
    build:
      context: /Users/hello/Desktop/ÉCOLE/DEVOPS/starrr/userapi
      dockerfile: Dockerfile
    container_name: projectdevopsssss
  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis
    volumes:
      - db-data:/data

volumes:
  db-data:

