apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-devops #Name of the deployment
  labels:
    app: project-devops
    version: v1
spec:
  replicas: 3 # represents the number of desired pods, here we use 3 replicas
  selector:
    matchLabels:
      app: project-devops # represents the label applied to pods 
  template:
    metadata:
      labels:
        app: project-devops 
        version: v1
    spec:
      containers:
        - name: project-devops
          image: alexben3005/userapi:latest  # Docker image for the container
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"  # We set it 512Mi to avoid problems
              cpu: "500m"      # We set it to half a CPU to avoid problems
          ports:
            - containerPort: 3000 # represents which port the container will be listening on
          volumeMounts:
            - mountPath: /var/lib/redis/
              name: storage-pvc
        - name: redis-deploy #redis deployment
          image: redis
          resources:
            limits:
              memory: "512Mi"  # Same as just before
              cpu: "500m"      
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis/
              name: storage-pvc
      volumes:
        - name: storage-pvc 
          persistentVolumeClaim: #We specify the PVC
            claimName: task-pv-claim  
