apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume # represents the name of the PersistentVolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" # path where the storage is located 