apiVersion: v1
kind: Service
metadata:
  name: project-devops-service #Name of the service
spec:
  type: NodePort #exposes the service on Nodes 
  selector:
    app: project-devops #selecting pods containing this label 
  ports:
    - name: http  # Add the protocol name as prefix
      port: 3000
      targetPort: 3000
