apiVersion: storage.k8s.io/v1 #specifying api version for storageclass
kind: StorageClass
metadata:
  name: manual #representing the name of the storage class
provisioner: k8s.io/minikube-hostpath #represents the provisionner for the storage which is Minikube


