apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim #represents the name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #asking for 1 gigabyte for the storage
