---
- name: Install required packages
  yum:
    name:
      - curl
      - policycoreutils-python
      - openssh-server
    state: latest

#Here we install npm, and node, to use them inside the VM
- name: Install npm
  yum:
    name: npm

- name: Install node 
  yum:
    name: nodejs

#Same thing for accessing redis inside the VM
- name: Install redis
  yum:
    name: redis
    state: latest

- name: Enable and start redis
  service:
    name: redis
    state: started
    enabled: yes

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: Enable HTTP+HTTPS access
  firewalld:
    # This is how we use a variable
    service: "{{ item }}"
    permanent: yes
    state: enabled
  # The module will be run for each item
  with_items:
    - http
    - https

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
  copy:
    src: /vagrant
    dest: /opt  
    follow: yes
  become: true