apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway #We use the ingressgateway provided by istio
  servers:
  - port:
      number: 8080 #gateway toward 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
  #name: service
#spec:
  #hosts:
    #- "*"
  #gateways:
    #- gateway
  #http:
    #- route:
        #- destination:
            #host: project-devops-service
            #port:
              #number: 3000
