apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project-devops-virtualservice
spec:
  hosts:
  - "*"
  gateways: 
  - gateway #we use the gateway that uses ingressgateway
  http:
  - route:
    - destination:
        host: project-devops-service
        subset: v1
      weight: 70 # 70 percent of the traffic goes to v1
    - destination:
        host: project-devops-service
        subset: v2
      weight: 30 # 30 percent of the traffic goes to v2
