apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: Kubernetes-bootcamp # Ensure this matches the labels of your target pods
  ports:
    - protocol: TCP
      port: 8080          
      targetPort: 8080    

    
