---
- name: Check Project health
  uri:
    url: http://192.168.56.64:3000/health #Check the health of the project
    return_content: yes
  register: project_health

- name: Print Project health
  debug:
    msg: "{{ project_health.content }}" #We print the project health

