name: Build and deploy Node.js app to Azure Web App - starrr-devops-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          cd userapi
          npm install
          npm run build --if-present
          # Add a delay to ensure Redis service is fully operational
          echo "Waiting for Redis to be ready..."
          sleep 10
          npm run test --if-present
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: userapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: userapi/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'starrr-devops-project'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D07E5FF7B07E434F8B7726DF45568DC3 }}
          # Set the production environment variables for Redis
          environment-variables: |
            REDIS_HOST= AlexSoso.redis.cache.windows.net // using redis cache to deploy
            REDIS_PORT= 6380
            
